name: stroke_canvas_flutter
description: Robotpen笔迹画布.
version: 0.0.9
homepage: http://www.robotpen.com
repository: https://github.com/PPWrite/stroke_canvas_flutter

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass