name: stroke_canvas_flutter
description: Robotpen笔迹画布.
version: 0.1.0
homepage: http://www.robotpen.com
repository: https://github.com/PPWrite/stroke_canvas_flutter

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass